[project]
name = "kcd-docs"
version = "1.0.0"
requires-python = ">=3.14"
dependencies = [
    "mkdocs==1.6.1",
    "mkdocs-git-revision-date-localized-plugin==1.5.0",
    "mkdocs-material==9.7.0",
    "mkdocs-open-in-new-tab==1.0.8",
]
